### ISSUE TITLE
missing pyoctree.cpp file

### ISSUE THREAD

**Issue by PeriniMatteo** [mhogg/pyoctree#21]
It seems that you missed the file pyoctree/pyoctree.cpp into the source code.
I can find it only into the packed release (pyoctree-0.2.4.tar.gz)
Thanks

**Comment by mhogg** [comment]
Hi Matteo,
Pyoctree.cpp is generated by Cython at compile time. It is therefore not part of the Github repository and not part of the source code (which is created by Github). That is why I upload pyoctree-0.2.4.tar.gz to the release so it is available. Does that make sense?
Cheers,
Michael
