### ISSUE TITLE
Get intersection of half the map, not full

### ISSUE THREAD

**Issue by shivaang12** [mhogg/pyoctree#27]
I have been trying to limit the ray to z direction but I am getting the intersection of full map.

**Comment by mhogg** [comment]
Hi,
I am not sure what you mean. Do you some code? Can you explain more what you are trying to achieve?
Michael

**Comment by shivaang12** [comment]
After following your python notebook code, I got the footprints of the below object. (IMAGE)

![00000](https://user-images.githubusercontent.com/9318164/43156773-095b2fc2-8f49-11e8-956b-da8e03181c84.png)

But what to do if I want the footprints of the above the black line area (See below Image).

![000001](https://user-images.githubusercontent.com/9318164/43156993-abfac7ce-8f49-11e8-89c2-7c1060994912.png)

**Comment by mhogg** [comment]
Hi,

Assuming that your z direction is up-down, x is left-right and y is into the screen, then you will need to modify the code used to generate the rays. That is, the current code is:

```
# Create rays
xs,xe,ys,ye,zs,ze = stl.GetBounds()
perc = 0.05
xr  = xe-xs
yr  = ye-ys
zr  = ze-zs
xs -= xr*perc
xe += xr*perc
ys -= yr*perc
ye += yr*perc
zs -= zr*perc
ze += zr*perc 
xr = np.linspace(xs,xe,width)
yr = np.linspace(ys,ye,height)
rayPointList = []
for x in xr:
    for y in yr:
        rayPointList.append([[x,y,zs],[x,y,ze]])
rayPointList = np.array(rayPointList,dtype=np.float32)
```
which you will need to swap the y and z. Then, to get the intersection only above the black line you would have to modify the value of zs. For example, to get the top half, do zs = zs + 0.5*(ze-zs):  
```
# Create rays
xs,xe,ys,ye,zs,ze = stl.GetBounds()
perc = 0.05
xr  = xe-xs
yr  = ye-ys
zr  = ze-zs
xs -= xr*perc
xe += xr*perc
ys -= yr*perc
ye += yr*perc
zs -= zr*perc
ze += zr*perc 
zs = zs + 0.5*(ze-zs)   # Added here so only get top half of trace
xr = np.linspace(xs,xe,width)
zr = np.linspace(zs,ze,height)
rayPointList = []
for x in xr:
    for z in zr:
        rayPointList.append([[x,ys,z],[x,ye,z]])
rayPointList = np.array(rayPointList,dtype=np.float32)
```
Hope this helps,
Michael

**Comment by shivaang12** [comment]
I have am changing the "zs" in my code but still I am getting the full intersection. Do you want to look into my code?

**Comment by mhogg** [comment]
Sure, happy to look at it. Send through a link.
Michael

**Comment by shivaang12** [comment]
https://drive.google.com/file/d/1z4KHv0RDXeJl_oK1hUFUmgYmXLsRjh8N/view?usp=sharing

Folder contains the instruction. Thanks for helping.

**Comment by shivaang12** [comment]
Thank you for your reply. But I think I might have confused you, sorry for that. I want this plane (see Image), above the black line in the first comment's image. Again thank you for everything.
![github](https://user-images.githubusercontent.com/9318164/43719602-26f5c20a-995c-11e8-9e80-ce98ac8b4306.png)

**Comment by mhogg** [comment]
Hopefully this is what you want, using different y values:

![image](https://user-images.githubusercontent.com/3631098/43751643-212dcaee-9a41-11e8-9e04-18a72ae61710.png)

The code changes I made to get this are below. Essentially I used the ```rayIntersection``` function rather than the ```rayIntersections```; this function gives more detail on the coordinates of the intersection points. I then filtered the intersection (or rather ```proj```) so that it only reports a hit if the y coordinate of the intersection point is above the value of ```ylim``` provided by the user. This is a bit slower to run, because ```rayIntersection``` is mainly in Python rather than C++, but it could be optimised.

```
def get_intersections(tree, ray_list, ranges, axis, ylim=0.0):
    """ generates projection of columns intersected by the rays """
    axis_b = (axis+1) % 3
    axis_c = (axis+2) % 3
    
    #proj = tree.rayIntersections(ray_list) # <<< REMOVED THIS
    
    intersections=[]
    for ray in ray_list:
        intersect = tree.rayIntersection(ray)
        intersections.append(intersect)
        
    proj=[]
    for intersect in intersections:
        result = 0
        for i in intersect:
            if i.p[1] > ylim:
                result = 1
        proj.append(result)
    proj = array(proj)
    
    print(proj.shape)
    proj = proj.reshape((ranges[axis_b],ranges[axis_c]))
    proj = proj.astype(float)
    return proj[::-1,:]

def generate_footprint(tree, obj, axis=1, ylim=0.0):
    """ generate axial projection of boundaries using raycasting on octree """ 
    mins, maxes = obj.get_bounds()
    [x_min, y_min, z_min] = mins
    [x_max, y_max, z_max] = maxes
    
    x_range, y_range, z_range = np.subtract(maxes,mins)
    x_range = int(x_range)
    y_range = int(y_range)
    z_range = int(z_range)

    x_incs = np.linspace(x_min,x_max,x_range)
    y_incs = np.linspace(y_min,y_max,y_range)
    z_incs = np.linspace(z_min,z_max,z_range)

    incs = [x_incs, y_incs, z_incs]
    ranges = [x_range, y_range, z_range]
    ray_list = get_rays(mins,maxes,incs,axis)
    return get_intersections(tree,ray_list,ranges,axis,ylim)

def main(filename='city1'):
    filename_obj = filename + '.obj'
    filename_pkl = filename + '.pkl'
    obj = Obj(f"./samples/{filename_obj}", model_size=500)
    tree = generate_octree(obj)
    proj = generate_footprint(tree,obj,axis=1,ylim=0.0)  # <<< Added ylim
    plot_projection(proj)

```

Hope this helps,
Michael

**Comment by shivaang12** [comment]
Ahh!! This is the thing which I was looking for. Thank you for your help. You are really a lifesaver!
