### ISSUE TITLE
Error compiling on Windows 10

### ISSUE THREAD

**Issue by mattbv** [mhogg/pyoctree#6]
Hi,

When trying to install via PyPi I get the following compilation error:

" C:\Users\user\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Include\xlocale(342) : warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc

  pyoctree\pyoctree.cpp(267) : fatal error C1083: Cannot open include file: 'cOctree.h': No such file or directory  error: command 'C:\\Users\\user\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\cl.exe' failed with exit status 2"

System:
Windows 10 Pro x64
Version 1511
Build 10586.545
Visual C++ 2008 (9.0) - MSC_VER=1500

If do you need any extra information, please just let me know.

Best regards.

**Comment by mhogg** [comment]
Hi mattbv,

For some reason cOctree.h is missing from the PyPi package. I will add it and upload a new version to PyPi soon.

In the meantime, you can get a copy of cOctree.h from Github [here] (https://github.com/mhogg/pyoctree/blob/master/pyoctree/cOctree.h). Just copy it to the same folder that contains cOctree.cpp and try to reinstall.

Alternatively you can either download the full source from Github (which contains all the files) or use the installer on the [releases page](https://github.com/mhogg/pyoctree/releases).

Cheers,
Michael

**Comment by mattbv** [comment]
Hi Michael,

Thank you for your quick reply. I've downloaded the source code and it worked, indeed. Also, nice to know that there's the option of a installer as well.

Cheers,
Matheus
