### ISSUE TITLE
OpenMP flag in compile args

### ISSUE THREAD

**Issue by dschouten** [mhogg/pyoctree#9]
Very interested in this package ... though haven't yet run it. 

If I try 'pip install pyoctree' in Linux, gcc fails with error "/openmp: No such file or directory", because of the extra_compile_args=['/openmp'] in setup.py ... I am guessing this is the flag for a Windows compiler? In Linux it is "-openmp" for icc and "-fopenmp" for gcc.

Thanks, Doug

**Comment by mhogg** [comment]
Hi Doug,

Yes, you are right. I have run it on Linux but typically use it on Windows.
I'll update it to detect the operating system so the correct openmp header
is called.

Cheers,
Michael

**Comment by mhogg** [comment]
Hi Doug,

I have created a new branch with an updated setup.py file that supplies the correct openmp arguments for each compiler. I have tested this on Windows only so far. I will test this shortly on linux, but it should work ok. If your interested, check it out. And thanks for the feedback.

Cheers,
Michael
